### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by andjelko** [mdmsoft/yii2-ar-behaviors#5]
When I update row i get different id on table items, why is that?
Extension works like unlink table items and again insert on update?

Thanks

**Comment by andjelko** [comment]
is there a possibility that does not change id in items table?

**Comment by mdmunir** [comment]
what behavior that you are using?
oh, i see... 
* add item id into `rules()`, make it safe attribute.
* provide item id at form as input (hidden input).

**Comment by andjelko** [comment]
I use RelationTrait

thank you so much,
working perfectly

cheers
